
Status: FAILED!
Reason: Unable to run Payroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/Payroll.py", line 25, in <module>
    print(f"Take-Home Pay: ${takeHomePay:.2f}")
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:18.932921

Status: FAILED!
Reason: Unable to run Payroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/Payroll.py", line 25, in <module>
    print(f"Take-Home Pay: ${takeHomePay:.2f}")
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:18.933071

Status: FAILED!
Reason: Unable to run Payroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/Payroll.py", line 25, in <module>
    print(f"Take-Home Pay: ${takeHomePay:.2f}")
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:19.024726

Status: FAILED!
Reason: Unable to run Payroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/Payroll.py", line 25, in <module>
    print(f"Take-Home Pay: ${takeHomePay:.2f}")
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:19.024825

Status: FAILED!
Reason: Unable to run tempPayroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/tempPayroll.py", line 10, in <module>
    print(f'Take-Home Pay: ${takeHomePay:.2f}')
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:19.102201

Status: FAILED!
Reason: Unable to run tempPayroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/tempPayroll.py", line 10, in <module>
    print(f'Take-Home Pay: ${takeHomePay:.2f}')
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:19.102297

Status: FAILED!
Reason: Unable to run tempPayroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/tempPayroll.py", line 10, in <module>
    print(f'Take-Home Pay: ${takeHomePay:.2f}')
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:19.178653

Status: FAILED!
Reason: Unable to run tempPayroll.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/9780357880876_pld-10e-python-8ddb5d1b-bece-4561-9ff4-f25ea7c30294/tempPayroll.py", line 10, in <module>
    print(f'Take-Home Pay: ${takeHomePay:.2f}')
NameError: name 'takeHomePay' is not defined

Timestamp: 2024-10-14 21:48:19.178737

Status: PASSED!
Check: 5
Test: Checking the program for hardcoded answers.
Reason: None
Timestamp: 2024-10-14 21:48:19.179167
